name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - master



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document BasicsMatricesVectors
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/BasicsMatricesVectors/

      - name: Compile LaTeX document 2D_vectors_and_lines
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/2D_vectors_and_lines/




      - name: Save BasicsMatricesVectors artifact
        uses: actions/upload-artifact@v1
        with:
          name: BasicsMatricesVectors.pdf
          path: Slides/BasicsMatricesVectors/main.pdf
          
      - name: Save 2D_vectors_and_lines artifact
        uses: actions/upload-artifact@v1
        with:
          name: 2D_vectors_and_lines.pdf
          path: Slides/2D_vectors_and_lines/main.pdf




      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/BasicsMatricesVectors/main.pdf
          git add Slides/2D_vectors_and_lines/main.pdf




          git commit -m "Update compiled PDFs"
          git push
